import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {

  const [dialogContent, setDialogContent] = useState({
    title: "Title",
    body: "Body" ,
    buttonText: "Button Text"
  })
  const [title, setTitle] = useState("tiket.com")
  const [snackbarMessage, setSnackbarMessage] = useState("Hello from Snackbar")
  const [externalUrl, setExternalUrl] = useState("https://google.com")
  const [openNewWebViewUrl, setOpenNewWebViewUrl] = useState("https://blibli.com")

  const forceExternal = (e) => {
    if(!!window.native) {
      window.native.forceExternal(externalUrl)
    }
  }

  const gotoPlayStore = (e) => {
    if(!!window.native) {
      window.native.gotoPlayStore()
    }
  }

  const closeWebView = (e) => {
    if(!!window.native) {
      window.native.closeWebView()
    }
  }

  const showNavbar = (e) => {
    if(!!window.native) {
      window.native.showNavbar()
    }
  }

  const hideNavbar = (e) => {
    if(!!window.native) {
      window.native.hideNavbar()
    }
  }

  const showLoading = (e) => {
    if(!!window.native) {
      window.native.showLoading()

      setTimeout(function (){
        window.native.hideLoading()
      }, 2000)
    }
  }

  const hideLoading = (e) => {
    if(!!window.native) {
      window.native.hideLoading()
    }
  }

  const openNewWebView = (e) => {
    if(!!window.native) {
      window.native.openNewWebView(openNewWebViewUrl)
    }
  }

  const setTitleWebView = (e) => {
    if(!!window.native) {
      window.native.setTitle(title)
    }
  }

  const showSnackbarDefault = (e) => {
    if(!!window.native) {
      window.native.showSnackBarDefault(snackbarMessage)
    }
  }

  const showSnackbarError = (e) => {
    if(!!window.native) {
      window.native.showSnackBarError(snackbarMessage)
    }
  }

  const showSnackbarSuccess = (e) => {
    if(!!window.native) {
      window.native.showSnackBarSuccess(snackbarMessage)
    }
  }

  const showDialog = (e) => {
    console.log(dialogContent)
    if(!!window.native) {
      window.native.showDialog(dialogContent.title, dialogContent.body, dialogContent.buttonText)
    }
  }

  return (
    <div>
      <Head>
        <title>PoC Web Common Actions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container p-8 bg-slate-100'>
        <div className="text-3xl font-bold pb-4 items-center">
          PoC Web Common Actions
        </div>

        <div className="grid grid-cols-1 gap-2">
          <button onClick={closeWebView} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Close WebView
          </button>
          <button className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Back Or Close
          </button>
          <button onClick={gotoPlayStore} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Open PlayStore
          </button>
          <button onClick={showNavbar} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Show Navbar
          </button>
          <button onClick={hideNavbar} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Hide Navbar
          </button>
          <button onClick={showLoading} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Show Loading
          </button>
          <button onClick={hideLoading} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Hide Loading
          </button>
          <div className="shadow-md rounded-md p-2 w-full bg-neutral-50 text-center">
            <input value={openNewWebViewUrl} onChange={ e => setOpenNewWebViewUrl(e.target.value) } className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-2" type="text"/>
            <button onClick={openNewWebView} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              Open New WebView
            </button>
          </div>
          <div className="shadow-md rounded-md p-2 w-full bg-neutral-50 text-center">
            <input value={externalUrl} onChange={ e => setExternalUrl(e.target.value) } className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-2" type="text"/>
            <button onClick={forceExternal} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              Force External
            </button>
          </div>
          <div className="shadow-md rounded-md p-2 w-full bg-neutral-50 text-center">
            <input value={title} onChange={ e => setTitle(e.target.value) } className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-2" type="text"/>
            <button onClick={setTitleWebView} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              Set Title
            </button>
          </div>
          <div className="shadow-md rounded-md p-2 w-full bg-neutral-50 text-center">
            <input value={snackbarMessage} onChange={ e => setSnackbarMessage(e.target.value) } className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-2" type="text"/>
            <button onClick={showSnackbarDefault} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              Show SnackBar Default
            </button>
          </div>
          <div className="shadow-md rounded-md p-2 w-full bg-neutral-50 text-center">
            <input value={snackbarMessage} onChange={ e => setSnackbarMessage(e.target.value) } className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-2" type="text"/>
            <button onClick={showSnackbarSuccess} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              Show SnackBar Success
            </button>
          </div>
          <div className="shadow-md rounded-md p-2 w-full bg-neutral-50 text-center">
            <input value={snackbarMessage} onChange={ e => setSnackbarMessage(e.target.value) } className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-2" type="text"/>
            <button onClick={showSnackbarError} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              Show SnackBar Error
            </button>
          </div>
          <div className="shadow-md rounded-md p-2 w-full bg-neutral-50 text-center">
            <input value={dialogContent.title} onChange={ e => setDialogContent({...dialogContent, title: e.target.value}) } className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-2" type="text"/>
            <input value={dialogContent.body} onChange={ e => setDialogContent({...dialogContent, body: e.target.value}) } className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-2" type="text"/>
            <input value={dialogContent.buttonText} onChange={ e => setDialogContent({...dialogContent, buttonText: e.target.value}) } className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-2" type="text"/>
            <button onClick={showDialog} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              Show Dialog
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
