import Head from 'next/head'
import Image from 'next/image'

export default function Home() {

  const gotoPlayStore = (e) => {
    if(!!window.native) {
      window.native.gotoPlayStore()
    }
  }

  const closeWebView = (e) => {
    if(!!window.native) {
      window.native.closeWebView()
    }
  }

  const showNavbar = (e) => {
    if(!!window.native) {
      window.native.showNavbar()
    }
  }

  const hideNavbar = (e) => {
    if(!!window.native) {
      window.native.hideNavbar()
    }
  }

  const showLoading = (e) => {
    if(!!window.native) {
      window.native.showLoading()
    }
  }

  const hideLoading = (e) => {
    if(!!window.native) {
      window.native.hideLoading()
    }
  }

  return (
    <div>
      <Head>
        <title>PoC Web Common Actions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container p-8 bg-slate-100'>
        <div className="text-3xl font-bold pb-4 items-center">
          PoC Web Common Actions
        </div>

        <div className="grid grid-cols-2 gap-2">
          <button onClick={closeWebView} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Close WebView
          </button>
          <button className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Back Or Close
          </button>
          <button onClick={gotoPlayStore} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Open PlayStore
          </button>
          <button className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Force External
          </button>
          <button onClick={showNavbar} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Show Navbar
          </button>
          <button onClick={hideNavbar} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Hide Navbar
          </button>
          <button onClick={showLoading} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Show Loading
          </button>
          <button onClick={hideLoading} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Hide Loading
          </button>
        </div>
      </div>
    </div>
  )
}
